### ISSUE TITLE
Installing Pumilio

### ISSUE THREAD

**Issue by PaolaMoscoso** [ljvillanueva/pumilio#53]
Hi, Is there any way to install the program without a Linux Operation System? Thanks

**Comment by ljvillanueva** [comment]
Thanks for your question. Unfortunately, the answer is no.

Linux was chosen because it allowed us to do many things more easily than a Windows server did. There would be a lot of edits in the code to make it work on Windows. Of course, anyone is welcome to try to adapt it, I can provide some guidance, but I don't have enough experience in a Windows Server to do it.
